version: '3.7'

services:
  db:
    container_name: springbootTesting
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: springboot_testing
      MYSQL_ROOT_PASSWORD: Secret123
      MYSQL_PASSWORD: Secret123
    volumes:
      - ./sql-data:/var/lib/mysql